import type { AgencyDitherOptions } from './types';

export const DEFAULT_OPTIONS: AgencyDitherOptions = {
  mode: 'dots',
  renderer: 'canvas',
  algorithm: 'bayer8',
  fit: 'cover',
  cellSize: 9,
  responsive: true,
  responsiveMinCellSize: 5,
  responsiveMaxCellSize: 18,
  responsiveReferenceWidth: 1200,
  resolutionScale: 1,
  maxDpr: 1.5,
  maxCells: 42_000,
  maxFps: 60,
  background: '#f1eee7',
  foreground: '#11110f',
  transparent: false,
  backgroundTransparent: false,
  foregroundTransparent: false,
  threshold: 0.5,
  ditherAmount: 0.85,
  contrast: 1.1,
  brightness: 0,
  gamma: 1,
  invert: false,
  blur: 0,
  dotScale: 0.92,
  symbolScale: 1,
  rotation: 0,
  noiseAmount: 0.08,
  noiseSpeed: 0.35,
  displacement: 0,
  rippleStrength: 0,
  mouseInfluence: 0,
  paletteMix: 1,
  glyphScramble: 0,
  revealProgress: 1,
  animationDuration: 1.4,
  ambientEnabled: false,
  ambientMode: 'drift',
  ambientAmount: 0.2,
  ambientSpeed: 0.6,
  ambientFrequency: 0.18,
  stagger: true,
  staggerAmount: 0.65,
  staggerFrom: 'start',
  maskProgress: 1,
  primitiveMix: 0.5,
  sourceMix: 0,
  maskInvert: false,
  maskThreshold: 0,
  maskFeather: 0.15,
  maskFit: 'contain',
  maskPositionX: 0.5,
  maskPositionY: 0.5,
  maskScale: 1,
  glyphRamp: ' .:,-=+*#%@',
  fontFamily: '"DM Mono", monospace',
  fontWeight: 500,
  colorMode: 'monochrome',
  palette: ['#11110f', '#ef5a37', '#f1eee7'],
  toneMap: [],
  animation: {
    autoplay: false,
    fps: 30,
    noiseSpeed: 0.35,
    glyphScramble: 0
  },
  interaction: {
    pointer: false,
    clickRipple: false
  },
  immediate: false,
  decorative: true,
  worker: true
};

export const REALTIME_ALGORITHMS = new Set([
  'threshold',
  'bayer2',
  'bayer4',
  'bayer8',
  'bayer16',
  'blue-noise',
  'random',
  'halftone'
]);
